### ISSUE TITLE
Wrong parameter in demo example causes TypeError

### ISSUE THREAD

**Issue by matmar10** [Askrround/botly#9]
Steps to reproduce:

- Follow intro demo instructions

Actual behavior:

```
TypeError: Cannot assign to read only property 'message' of 1214502681935759
   at Botly.router.Botly.getPSID.Botly.getUserProfile.Botly.setGetStarted.Botly.setPersistentMenu.Botly.send.Botly.sendAction.Botly.sendText (/app/node_modules/botly/lib/Botly.js:245:21)
   at Botly.<anonymous> (/app/index.js:24:11)
   at Botly.emit (events.js:188:7)
   at Botly._handleUserMessage (/app/node_modules/botly/lib/Botly.js:386:14)
   at emitThree (events.js:110:13)
   at Botly.<anonymous> (/app/node_modules/botly/lib/Botly.js:334:32)
   at Array.forEach (native)
   at Botly.<anonymous> (/app/node_modules/botly/lib/Botly.js:329:25)
   at Botly.router.Botly.getPSID.Botly.getUserProfile.Botly.setGetStarted.Botly.setPersistentMenu.Botly.send.Botly.sendAction.Botly.handleMessage.body.entry.forEach [as handleMessage] (/app/node_modules/botly/lib/Botly.js:328:16)
   at Array.forEach (native)
   at=info method=POST path="/webhook/" host=lit-fjord-55925.herokuapp.com request_id=3450cd2d-9b2f-4485-9e1b-4210842b104a fwd="173.252.88.183" dyno=web.1 connect=1ms service=4ms status=200 bytes=196
   at Botly.<anonymous> (/app/index.js:24:11)
TypeError: Cannot assign to read only property 'message' of 1214502681935759
   at Botly.router.Botly.getPSID.Botly.getUserProfile.Botly.setGetStarted.Botly.setPersistentMenu.Botly.send.Botly.sendAction.Botly.sendText (/app/node_modules/botly/lib/Botly.js:245:21)
   at Botly.emit (events.js:188:7)
   at Botly.<anonymous> (/app/node_modules/botly/lib/Botly.js:334:32)
   at emitThree (events.js:110:13)
   at Botly._handleUserMessage (/app/node_modules/botly/lib/Botly.js:386:14)
   at Botly.<anonymous> (/app/node_modules/botly/lib/Botly.js:329:25)
   at Array.forEach (native)
   at Array.forEach (native)
   at Botly.router.Botly.getPSID.Botly.getUserProfile.Botly.setGetStarted.Botly.setPersistentMenu.Botly.send.Botly.sendAction.Botly.handleMessage.body.entry.forEach [as handleMessage] (/app/node_modules/botly/lib/Botly.js:328:16)
```
- Expected behavior: acks Facebook callback without erro

Due to invalid argument (should be object)

**Comment by miki2826** [comment]
Thanks. merged
